default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_pass] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: health_unit_radar_development

test:
  <<: *default
  database: health_unit_radar_test

production:
  <<: *default
  database: health_unit_radar_production
  username: health_unit_radar
  password: <%= ENV['HEALTH_UNIT_RADAR_DATABASE_PASSWORD'] %>
